### ISSUE TITLE
Nieuw grootboek aan maken

### ISSUE THREAD

**Issue by Chantalnoest** [stefanius/qs-finance2#12]
Gaarne een optie om nieuwe grootboeken aan te maken

**Comment by stefanius** [comment]
U vraagt, wij draaien.  In het steeksleutel menu kan je grootboeken beheren, aanmaken en verwijderen. Het verwijderen kan alleen bij grootboeken waar nog nooit een boeking op is geweest. Als er ooit in de tijd een 1 boeking op een grootboek is gemaakt, is het niet mogelijk om het grootboek te verwijderen.
