### ISSUE TITLE
Password wijzigen

### ISSUE THREAD

**Issue by Chantalnoest** [stefanius/qs-finance2#13]
Gaarne een optie om je password te wijzigen of misschien nog wel een must na ? een jaar?

**Comment by stefanius** [comment]
Eens. Ga ik maken. Weet nog niet of het nu of iets later aangepast word.

**Comment by stefanius** [comment]
U vraagt wij draaien. De optie zit erin. Ga ikuitleggen zodra we live gaan (niet alvast stiekum uitproberen ;) )
