### ISSUE TITLE
Kolommenbalans in prog

### ISSUE THREAD

**Issue by Chantalnoest** [stefanius/qs-finance2#14]
Graag de optie weer terug dat je in het programma de kolommenbalans kan zien. En natuurlijk daarop kan klikken om de nodige transacties te kunnen laten zien. Want dan kan ik lekker klikken :-)

**Comment by stefanius** [comment]
Kolomenbalans in oude glorie hersteld. Ook zijn er 3 overzichten gemaakt waarin de totalen van Deber, Credit en het saldo word getoond. Deze overzichten en de kolombalans is te vinden in het menu 'Balans' in de grijze menubalk bovenin het scherm. Het menu 'Balans' is overigens alleen zichtbaar als je een in een boekjaar zit.
