### ISSUE TITLE
bank import

### ISSUE THREAD

**Issue by Chantalnoest** [stefanius/qs-finance2#15]
Bij het importeren van een bank bestand. Bv een maand, vervalt constant de eerste regel. Is dit een fout bij mij ? Of bij het bestand ? Zou je er eens naar willen kijken want nu boek ik de eerste regel als nog los en apart in.

**Comment by stefanius** [comment]
Is het Rabo of ING? Kan je mij de CSV mailen?

**Comment by Chantalnoest** [comment]
voorlopig ben ik alleen nog maar met de rabo bezig. zal het mailen

**Comment by stefanius** [comment]
Top. Dank u. heb m ontvangen

2013/12/5 Chantalnoest notifications@github.com
