### ISSUE TITLE
auto log out

### ISSUE THREAD

**Issue by Chantalnoest** [stefanius/qs-finance2#16]
Als je iets wat te lang doet over het zoeken van (bv een bonnetje ;-)) dan logt die automatisch uit het systeem :-( met gevolg dat je weer moet inloggen en dat je dan net je gehele bankboeking kwijt bent. Kan je hier eens naar kijken of daar een tijd op staat ?

**Comment by stefanius** [comment]
Ga ik regelen!

**Comment by stefanius** [comment]
Er stond geen timeout ingesteld. Standaard is de tijd inactief idd er
weinig. Ik heb hem nu op 60 minuten gezet in de nieuwe versie. Dit betekend
dat je tussen 2 handelingen maximaal 60 minuten niks mag doen. Hierna logt
hij weer uit. 60 minuten lijkt mij ruim de tijd, als je denkt meer nodig te
hebben, hoor ik dat graag ;)

Op 1 december 2013 21:22 schreef Chantalnoest notifications@github.com:
