### ISSUE TITLE
Cross boeking bij bank

### ISSUE THREAD

**Issue by Chantalnoest** [stefanius/qs-finance2#17]
Deze staat nu geheel onderaan; niet handig. Bovenin of links zou denk ik beter zijn

**Comment by stefanius** [comment]
Ik snap het issue niet? Bedoel je de link? Ik sluit het issue overigens wel. Dit gaat over de oude versie, kijk even naar de nieuwe versie en maak een nieuw issue aan als je iets ervan anders wilt zien ;)
