### ISSUE TITLE
Boekdatum/geld bedrag import

### ISSUE THREAD

**Issue by Chantalnoest** [stefanius/qs-finance2#18]
Bij het importeren van een bank, zijn de tabellen van de datum en geld wat klein. Meer en deel valt eraf. En de datum staat als yyyy/mm/dd misschien is het handiger om er dd/mm/yyyy van te maken, dan hoeft die ook niet perse breeder

**Comment by stefanius** [comment]
Opgelost. Ik wil het scherm nog wel een update geven, maar voorlopig is het denk ik wel OK. Als je andere sugestie hebt over de indeling van dit scherm, hoor ik dat graag.
