### ISSUE TITLE
Nakijken gemaakte boeking

### ISSUE THREAD

**Issue by Chantalnoest** [stefanius/qs-finance2#19]
Als ik op een boeking klik, bij de bank, kan ik niet zien op welk grootboek die is geboekt dan wel andere gegevens. Ik krijg wel een Error.

**Comment by stefanius** [comment]
Ow errors zijn sowiezo kut ;) kan je mij de error sturen en de
uiteindelijke link (url) die je in browser ziet geven? Kan dan gewoon in
dit ticktet.

Op 5 december 2013 22:14 schreef Chantalnoest notifications@github.com:

**Comment by Chantalnoest** [comment]
een voorbeeldje van een error:

http://brigittavalentijn.qs-finance.nl/calculations/view/52a236db-17e4-4f82-b8e7-1305b90a3350

**Comment by stefanius** [comment]
Opgelost in nieuwe versie, kijk op staging.qs-finance.nl.
