### ISSUE TITLE
Kleur/layout

### ISSUE THREAD

**Issue by Chantalnoest** [stefanius/qs-finance2#21]
Ik weet niet of ik deze al eerder had gemeld maar als een boeking succesvol is geboekt is het kader daaromheen rood. Dat ziet er niet heel best uit, groen zou een betere kleur zijn, als het dan toch goed is.

**Comment by stefanius** [comment]
Ik heb nettere Flashmessages geintroduceerd op basis van Bootstrap-layouts. Deze zijn beschikbaar in 4 kleuren die elk een eigen type melding visueel maken. Ik heb een aantal meldingen al herschreven, en vertaald naar het Nederlands, maar nog lang niet alle meldingen zijn OK. Als je meldingen tegenkomt in het Engels en/of in een verkeerde (of geen kleur) of uberhaupt een melding verwacht maar niet krijgt, dan graag in een nieuw issue laten weten.
