### ISSUE TITLE
Gegevens blijven staan

### ISSUE THREAD

**Issue by Chantalnoest** [stefanius/qs-finance2#23]
Bij een losse (bv) bankboeking, blijf je huidig in het crossboeking systeem staan. Nadat je een boeking hebt toegevoegd. 

Als je dan bv eerst een credit boeking hebt gedaan en daarna wil je nog een debet boeking doen dan staat de data van de boeking, van de vorige, nog bij de credit. Dit moet je dus eerst weghalen voordat je een nieuwe boeking kan doen. Je krijgt niet een automatisch leeg veld zeg maar.

**Comment by stefanius** [comment]
Solved. Ik sluit het issue; het boekingsscherm is sowiezo aangepast in de nieuwe versie. Kijk er even naar en geef je oordeel. Ik sluit het issue.
