### ISSUE TITLE
CSV

### ISSUE THREAD

**Issue by Chantalnoest** [stefanius/qs-finance2#25]
Bij het inladen van CSV bestanden van de bank, bij het invoeren van de tegenrekening een stop zetten op enter/ er voor zorgen dat je dan niet gelijk je csv kwijt bent dingens. Zoals telefonisch besproken en als je er niet uitkomt hoor ik het wel.

**Comment by stefanius** [comment]
Opgelost, @Chantalnoest  zie hiervoor de import. Graag feedback.
