### ISSUE TITLE
Saldo vieuw

### ISSUE THREAD

**Issue by Chantalnoest** [stefanius/qs-finance2#28]
Kan het saldo van een grootboek bovenaan staan ? En wellicht wat groter dan dat het nou is. Mag best opvallen. Misschien ook dik gedrukt ?

**Comment by stefanius** [comment]
Solved. Ik heb nu linksboven de totalen staan. Dit is een tijdelijke oplossing, ik wil dit uiteraard een netterre look geven. Tips / wensen hierover zijn welkom.
